version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - STORAGE=csv
      - MODEL=xgboost
      - VERSION=v2
      - STORAGE_PATH=/app/data/transactions.csv
      - FEATURES_PATH=/app/data/interim/features_v2.yaml
      - MODELS_PATH=/app/data/models
      - THRESHOLDS_PATH=/app/data/models/thresholds.yaml
    volumes:
      - ./data:/app/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - STORAGE=csv
      - MODEL=xgboost
      - VERSION=v2
      - STORAGE_PATH=/app/data/transactions.csv
      - FEATURES_PATH=/app/data/interim/features_v2.yaml
      - MODELS_PATH=/app/data/models
      - THRESHOLDS_PATH=/app/data/models/thresholds.yaml
    volumes:
      # Mount data directory for development (optional)
      - ./data:/app/data:ro
    command: ["uv", "run", "pytest", "tests/", "--cov=api"]

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: ml
    container_name: ml-notebooks
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    environment:
      - NB_UID=${NB_UID}
      - NB_GID=${NB_GID}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    command:
      - uv
      - run
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --no-browser
      - --ServerApp.root_dir=/app/notebooks
      - --ServerApp.token=
      - --ServerApp.password=
      - --ServerApp.allow_origin=*
    restart: unless-stopped
    